In [1]:
import yfinance as yf

In [2]:
ticker = yf.Ticker('AAPL')

In [4]:
ticker.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allows customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'Executive Chairman of the Board',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. John  Ternus',
   'age': 49,
   'title': 'CEO & Director',
   'yearBorn': 1976,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 55,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1970,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 6,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1788220800,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 332.27,
 'open': 334.83,
 'dayLow': 331.34,
 'dayHigh': 335.5,
 'regularMarketPreviousClose': 332.27,
 'regularMarketOpen': 334.83,
 'regularMarketDayLow': 331.34,
 'regularMarketDayHigh': 335.5,
 'dividendRate': 1.08,
 'dividendYield': 0.33,
 'exDividendDate': 1786320000,
 'payoutRatio': 0.1204,
 'fiveYearAvgDividendYield': 0.5,
 'beta': 1.085,
 'trailingPE': 38.2411,
 'forwardPE': 34.757923,
 'volume': 38702066,
 'regularMarketVolume': 38702066,
 'averageVolume': 53820953,
 'averageVolume10days': 46608900,
 'averageDailyVolume10Day': 46608900,
 'bid': 333.12,
 'ask': 350.0,
 'bidSize': 5,
 'askSize': 1,
 'marketCap': 4861029515264,
 'nonDilutedMarketCap': 4849208188600,
 'fiftyTwoWeekLow': 235.03,
 'fiftyTwoWeekHigh': 344.57,
 'allTimeHigh': 344.57,
 'allTimeLow': 0.049107,
 'fulldayPrice': 331.0,
 'fulldayChange': -2.2099915,
 'fulldayChangePercent': -0.66350174,
 'priceToSalesTrailing12Months': 10.413004,
 'fiftyDayAverage': 318.4632,
 'twoHundredDayAverage': 285.23914,
 'trailingAnnualDividendRate': 1.05,
 'trailingAnnualDividendYield': 0.0031600806,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4882974638080,
 'profitMargins': 0.27618998,
 'floatShares': 14569078010,
 'sharesOutstanding': 14594180000,
 'sharesShort': 139749097,
 'sharesShortPriorMonth': 141606163,
 'sharesShortPreviousMonthDate': 1785456000,
 'dateShortInterest': 1788134400,
 'sharesPercentSharesOut': 0.0095999995,
 'heldPercentInsiders': 0.01648,
 'heldPercentInstitutions': 0.66339993,
 'shortRatio': 2.97,
 'shortPercentOfFloat': 0.0095999995,
 'impliedSharesOutstanding': 14594180000,
 'bookValue': 7.36,
 'priceToBook': 45.255432,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1782518400,
 'earningsQuarterlyGrowth': 0.271,
 'netIncomeToCommon': 128929996800,
 'trailingEps': 8.71,
 'forwardEps': 9.58285,
 'pegRatio': 2.61,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 10.46,
 'enterpriseToEbitda': 29.072,
 '52WeekChange': 0.4071821,
 'SandP52WeekChange': 0.15187562,
 'lastDividendValue': 0.27,
 'lastDividendDate': 1786320000,
 'quoteType': 'EQUITY',
 'currentPrice': 333.08,
 'targetHighPrice': 400.0,
 'targetLowPrice': 215.0,
 'targetMeanPrice': 325.65796,
 'targetMedianPrice': 335.0,
 'recommendationMean': 2.18182,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 39,
 'totalCash': 62399000576,
 'totalCashPerShare': 4.276,
 'ebitda': 167959003136,
 'totalDebt': 84343996416,
 'quickRatio': 0.812,
 'currentRatio': 1.003,
 'totalRevenue': 466822987776,
 'debtToEquity': 78.445,
 'revenuePerShare': 31.707,
 'returnOnAssets': 0.27082002,
 'returnOnEquity': 1.4875101,
 'grossProfits': 227123003392,
 'freeCashflow': 107721875456,
 'operatingCashflow': 146723995648,
 'earningsGrowth': 0.287,
 'revenueGrowth': 0.164,
 'grossMargins': 0.48653,
 'ebitdaMargins': 0.35979,
 'operatingMargins': 0.32623002,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'preMarketTime': 1789465151,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketTime': 1789416001,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'regularMarketChangePercent': 0.243777,
 'regularMarketPrice': 333.08,
 'averageDailyVolume3Month': 53820953,
 'fiftyTwoWeekLowChange': 98.04999,
 'fiftyTwoWeekLowChangePercent': 0.41718075,
 'fiftyTwoWeekRange': '235.03 - 344.57',
 'fiftyTwoWeekHighChange': -11.490021,
 'fiftyTwoWeekHighChangePercent': -0.033345968,
 'fiftyTwoWeekChangePercent': 40.71821,
 'dividendDate': 1786579200,
 'earningsTimestamp': 1785441600,
 'earningsTimestampStart': 1793304000,
 'earningsTimestampEnd': 1793304000,
 'earningsCallTimestampStart': 1785441600,
 'earningsCallTimestampEnd': 1785441600,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 8.71,
 'epsForward': 9.58285,
 'epsCurrentYear': 8.82929,
 'priceEpsCurrentYear': 37.724434,
 'fiftyDayAverageChange': 14.616791,
 'fiftyDayAverageChangePercent': 0.045897897,
 'twoHundredDayAverageChange': 47.84085,
 'twoHundredDayAverageChangePercent': 0.1677219,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.2 - Buy',
 'cryptoTradeable': False,
 'marketState': 'PRE',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'preMarketChange': -2.0799866,
 'preMarketChangePercent': -0.6244706,
 'preMarketPrice': 331.0,
 'regularMarketChange': 0.809998,
 'regularMarketDayRange': '331.34 - 335.5',
 'fullExchangeName': 'NasdaqGS',
 'displayName': 'Apple',
 'trailingPegRatio': 2.6068}

In [5]:
ticker.calendar

{'Dividend Date': datetime.date(2026, 8, 13),
 'Ex-Dividend Date': datetime.date(2026, 8, 10),
 'Earnings Date': [datetime.date(2026, 10, 30)],
 'Earnings High': 2.07,
 'Earnings Low': 1.93,
 'Earnings Average': 1.98124,
 'Revenue High': 117219700000,
 'Revenue Low': 112248100000,
 'Revenue Average': 113624521680}

In [6]:
ticker.analyst_price_targets

{'current': 333.08,
 'high': 400.0,
 'low': 215.0,
 'mean': 325.65796,
 'median': 335.0}

In [7]:
ticker.quarterly_income_stmt

,2026-06-30,2026-03-31,2025-12-31,2025-09-30,2025-06-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,1.786200e-01,1.750000e-01,1.750000e-01,1.627240e-01,1.639970e-01
Normalized EBITDA,3.901500e+10,3.932400e+10,5.406600e+10,3.555400e+10,3.103200e+10
Net Income From Continuing Operation Net Minority Interest,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Reconciled Depreciation,3.320000e+09,3.439000e+09,3.214000e+09,3.127000e+09,2.830000e+09
Reconciled Cost Of Revenue,5.464700e+10,5.640300e+10,7.452500e+10,5.412500e+10,5.031800e+10
EBITDA,3.901500e+10,3.932400e+10,5.406600e+10,3.555400e+10,3.103200e+10
EBIT,3.569500e+10,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10
Normalized Income,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income From Continuing And Discontinued Operation,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Total Expenses,7.372200e+10,7.529900e+10,9.290400e+10,7.003900e+10,6.583400e+10
Total Operating Income As Reported,3.569500e+10,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10
Diluted Average Shares,1.471468e+10,1.472587e+10,1.481036e+10,1.486361e+10,1.494818e+10
Basic Average Shares,1.465611e+10,1.467328e+10,1.474816e+10,1.481531e+10,1.490289e+10
Diluted EPS,2.020000e+00,2.010000e+00,2.840000e+00,1.850000e+00,1.570000e+00
Basic EPS,2.030000e+00,2.020000e+00,2.850000e+00,1.850000e+00,1.570000e+00
Diluted NI Availto Com Stockholders,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income Common Stockholders,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income Including Noncontrolling Interests,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Net Income Continuous Operations,2.978900e+10,2.957800e+10,4.209700e+10,2.746600e+10,2.343400e+10
Tax Provision,6.478000e+09,6.255000e+09,8.905000e+09,5.338000e+09,4.597000e+09
Pretax Income,3.626700e+10,3.583300e+10,5.100200e+10,3.280400e+10,2.803100e+10
Other Income Expense,5.720000e+08,-5.200000e+07,1.500000e+08,3.770000e+08,-1.710000e+08
Other Non Operating Income Expenses,5.720000e+08,-5.200000e+07,1.500000e+08,3.770000e+08,-1.710000e+08
Operating Income,3.569500e+10,3.588500e+10,5.085200e+10,3.242700e+10,2.820200e+10
Operating Expense,1.907500e+10,1.889600e+10,1.837900e+10,1.591400e+10,1.551600e+10
Research And Development,1.172900e+10,1.141900e+10,1.088700e+10,8.866000e+09,8.866000e+09
Selling General And Administration,7.346000e+09,7.477000e+09,7.492000e+09,7.048000e+09,6.650000e+09
Gross Profit,5.477000e+10,5.478100e+10,6.923100e+10,4.834100e+10,4.371800e+10
Cost Of Revenue,5.464700e+10,5.640300e+10,7.452500e+10,5.412500e+10,5.031800e+10
Total Revenue,1.094170e+11,1.111840e+11,1.437560e+11,1.024660e+11,9.403600e+10
Operating Revenue,1.094170e+11,1.111840e+11,1.437560e+11,1.024660e+11,9.403600e+10

In [8]:
ticker.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-17 00:00:00-04:00,306.209991,307.660004,302.940002,305.589996,38169300,0.0,0.0
2026-08-18 00:00:00-04:00,307.579987,311.489990,305.739990,310.029999,53424500,0.0,0.0
2026-08-19 00:00:00-04:00,310.140015,319.279999,309.600006,316.829987,50505600,0.0,0.0
2026-08-20 00:00:00-04:00,317.459991,320.279999,310.649994,311.299988,40959200,0.0,0.0
2026-08-21 00:00:00-04:00,312.049988,312.380005,307.010010,309.350006,46876800,0.0,0.0
2026-08-24 00:00:00-04:00,311.470001,313.359985,309.970001,310.339996,34673600,0.0,0.0
2026-08-25 00:00:00-04:00,310.790009,313.589996,308.209991,309.899994,25869800,0.0,0.0
2026-08-26 00:00:00-04:00,310.299988,315.429993,308.799988,313.450012,34024500,0.0,0.0
2026-08-27 00:00:00-04:00,310.549988,315.399994,309.399994,314.579987,32419200,0.0,0.0
2026-08-28 00:00:00-04:00,316.850006,322.369995,315.450012,319.700012,38649400,0.0,0.0
2026-08-31 00:00:00-04:00,319.600006,321.239990,312.799988,316.850006,41242700,0.0,0.0
2026-09-01 00:00:00-04:00,316.980011,327.299988,314.730011,325.130005,53167400,0.0,0.0
2026-09-02 00:00:00-04:00,326.869995,328.399994,323.529999,324.959991,33776400,0.0,0.0
2026-09-03 00:00:00-04:00,324.869995,330.809998,324.109985,328.209991,37225800,0.0,0.0
2026-09-04 00:00:00-04:00,328.309998,328.929993,317.859985,319.970001,39606900,0.0,0.0
2026-09-08 00:00:00-04:00,317.100006,320.700012,314.899994,316.220001,35477100,0.0,0.0
2026-09-09 00:00:00-04:00,315.489990,319.149994,309.899994,315.339996,65640000,0.0,0.0
2026-09-10 00:00:00-04:00,316.670013,326.739990,316.510010,326.570007,70011900,0.0,0.0
2026-09-11 00:00:00-04:00,327.450012,336.220001,326.299988,332.269989,50716900,0.0,0.0
2026-09-14 00:00:00-04:00,334.790009,335.500000,331.339996,333.079987,39223900,0.0,0.0

In [9]:
ticker.option_chain(ticker.options[0]).calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260916C00255000,2026-09-14 19:51:21+00:00,255.0,79.33,0.0,0.0,0.0,0.0,3.0,0,0.000010,True,REGULAR,USD
1,AAPL260916C00260000,2026-09-14 19:46:34+00:00,260.0,74.06,0.0,0.0,0.0,0.0,6.0,0,0.000010,True,REGULAR,USD
2,AAPL260916C00265000,2026-09-14 19:35:12+00:00,265.0,69.95,0.0,0.0,0.0,0.0,4.0,0,0.000010,True,REGULAR,USD
3,AAPL260916C00275000,2026-09-08 18:59:54+00:00,275.0,41.13,0.0,0.0,0.0,0.0,NaN,0,0.000010,True,REGULAR,USD
4,AAPL260916C00280000,2026-09-14 19:27:51+00:00,280.0,54.42,0.0,0.0,0.0,0.0,4.0,0,0.000010,True,REGULAR,USD
5,AAPL260916C00285000,2026-09-14 19:46:29+00:00,285.0,49.06,0.0,0.0,0.0,0.0,5.0,0,0.000010,True,REGULAR,USD
6,AAPL260916C00290000,2026-09-10 18:39:14+00:00,290.0,34.08,0.0,0.0,0.0,0.0,13.0,0,0.000010,True,REGULAR,USD
7,AAPL260916C00295000,2026-09-14 15:16:27+00:00,295.0,38.38,0.0,0.0,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD
8,AAPL260916C00300000,2026-09-14 15:48:18+00:00,300.0,35.00,0.0,0.0,0.0,0.0,15.0,0,0.000010,True,REGULAR,USD
9,AAPL260916C00302500,2026-09-11 13:42:58+00:00,302.5,31.37,0.0,0.0,0.0,0.0,NaN,0,0.000010,True,REGULAR,USD
10,AAPL260916C00305000,2026-09-14 17:27:47+00:00,305.0,29.57,0.0,0.0,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD
11,AAPL260916C00307500,2026-09-14 15:05:27+00:00,307.5,25.25,0.0,0.0,0.0,0.0,1.0,0,0.000010,True,REGULAR,USD
12,AAPL260916C00310000,2026-09-14 18:47:54+00:00,310.0,24.85,0.0,0.0,0.0,0.0,2.0,0,0.000010,True,REGULAR,USD
13,AAPL260916C00312500,2026-09-14 18:36:12+00:00,312.5,21.63,0.0,0.0,0.0,0.0,6.0,0,0.000010,True,REGULAR,USD
14,AAPL260916C00315000,2026-09-14 19:59:14+00:00,315.0,18.44,0.0,0.0,0.0,0.0,210.0,0,0.000010,True,REGULAR,USD
15,AAPL260916C00317500,2026-09-14 17:53:09+00:00,317.5,17.03,0.0,0.0,0.0,0.0,110.0,0,0.000010,True,REGULAR,USD
16,AAPL260916C00320000,2026-09-14 19:58:51+00:00,320.0,13.61,0.0,0.0,0.0,0.0,247.0,0,0.000010,True,REGULAR,USD
17,AAPL260916C00322500,2026-09-14 19:58:51+00:00,322.5,11.11,0.0,0.0,0.0,0.0,83.0,0,0.000010,True,REGULAR,USD
18,AAPL260916C00325000,2026-09-14 19:55:00+00:00,325.0,9.35,0.0,0.0,0.0,0.0,614.0,0,0.000010,True,REGULAR,USD
19,AAPL260916C00327500,2026-09-14 19:58:53+00:00,327.5,6.70,0.0,0.0,0.0,0.0,1475.0,0,0.000010,True,REGULAR,USD
20,AAPL260916C00330000,2026-09-14 19:59:53+00:00,330.0,4.62,0.0,0.0,0.0,0.0,4400.0,0,0.000010,True,REGULAR,USD
21,AAPL260916C00332500,2026-09-14 19:59:59+00:00,332.5,3.00,0.0,0.0,0.0,0.0,15772.0,0,0.000010,True,REGULAR,USD
22,AAPL260916C00335000,2026-09-14 19:59:59+00:00,335.0,1.87,0.0,0.0,0.0,0.0,33699.0,0,0.015635,False,REGULAR,USD
23,AAPL260916C00337500,2026-09-14 19:59:59+00:00,337.5,1.10,0.0,0.0,0.0,0.0,13902.0,0,0.031260,False,REGULAR,USD
24,AAPL260916C00340000,2026-09-14 19:59:57+00:00,340.0,0.58,0.0,0.0,0.0,0.0,19854.0,0,0.062509,False,REGULAR,USD
25,AAPL260916C00342500,2026-09-14 19:59:57+00:00,342.5,0.31,0.0,0.0,0.0,0.0,10808.0,0,0.062509,False,REGULAR,USD
26,AAPL260916C00345000,2026-09-14 19:59:59+00:00,345.0,0.17,0.0,0.0,0.0,0.0,6789.0,0,0.125009,False,REGULAR,USD
27,AAPL260916C00347500,2026-09-14 19:59:58+00:00,347.5,0.08,0.0,0.0,0.0,0.0,2827.0,0,0.125009,False,REGULAR,USD
28,AAPL260916C00350000,2026-09-14 19:59:59+00:00,350.0,0.05,0.0,0.0,0.0,0.0,3694.0,0,0.125009,False,REGULAR,USD
29,AAPL260916C00352500,2026-09-14 19:54:22+00:00,352.5,0.03,0.0,0.0,0.0,0.0,1145.0,0,0.125009,False,REGULAR,USD
30,AAPL260916C00355000,2026-09-14 19:58:34+00:00,355.0,0.01,0.0,0.0,0.0,0.0,807.0,0,0.250007,False,REGULAR,USD
31,AAPL260916C00360000,2026-09-14 19:47:12+00:00,360.0,0.01,0.0,0.0,0.0,0.0,2417.0,0,0.250007,False,REGULAR,USD
32,AAPL260916C00365000,2026-09-14 19:29:14+00:00,365.0,0.01,0.0,0.0,0.0,0.0,33.0,0,0.250007,False,REGULAR,USD
33,AAPL260916C00370000,2026-09-14 19:59:21+00:00,370.0,0.01,0.0,0.0,0.0,0.0,2.0,0,0.250007,False,REGULAR,USD
34,AAPL260916C00375000,2026-09-14 13:36:27+00:00,375.0,0.01,0.0,0.0,0.0,0.0,1.0,0,0.250007,False,REGULAR,USD
35,AAPL260916C00380000,2026-09-11 19:44:18+00:00,380.0,0.01,0.0,0.0,0.0,0.0,39.0,0,0.500005,False,REGULAR,USD
36,AAPL260916C00385000,2026-09-08 17:00:50+00:00,385.0,0.07,0.0,0.0,0.0,0.0,2.0,0,0.500005,False,REGULAR,USD
37,AAPL260916C00390000,2026-09-14 16:13:03+00:00,390.0,0.05,0.0,0.0,0.0,0.0,1.0,0,0.500005,False,REGULAR,USD

In [12]:
tickers = yf.Tickers('MSFT AAPL GOOG')
tickers.tickers['MSFT'].info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "Microsoft Corporation, a technology company, develops and supports a portfolio of technology solutions for individuals and businesses worldwide. Its products include operating systems, server applications, business solution applications, software development tools, desktop and server management tools, and video games; and devices, such as PCs, tablets, gaming and entertainment consoles, other intelligent devices, and related accessories. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Power BI, Exchange, SharePoint, Microsoft Teams, Microsoft 365 Security and Compliance, Microsoft 365 Copilot, and Windows Commercial on-premises and Office licensed on-premises. This segment also provides Microsoft 365 Consumer products and cloud services; LinkedIn, including talent solutions, marketing solutions, subscriptions, and sales solutions; Dynamics 365, a set of cloud-based applications; and on-premises ERP and CRM applications. Its Intelligent Cloud segment offers server products and cloud services; cloud and AI consumption-based services, GitHub cloud services, health and life sciences cloud services, as well as virtual desktop offerings, and other cloud services; SQL Server, Windows Server, Visual Studio, System Center, and related client access licenses; and enterprise support services, industry solutions, Microsoft partner network, and learning experience. The company's More Personal Computing segment provides Windows OEM licensing and devices comprising Surface and PC accessories; XBOX hardware, and XBOX first- and third-party content and services; XBOX Game Pass and other subscriptions; XBOX Cloud Gaming, advertising, and other cloud services; and search advertising consisting of Bing, Copilot, Microsoft News, Microsoft Edge, and third-party affiliates. It sells its products through partners and retail networks. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'fullTimeEmployees': 223000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 58,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 12251294,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 66,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2025,
   'totalPay': 4532750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 53,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4444191,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 54,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'totalPay': 2871250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 52,
   'title': 'Executive VP & CEO of Commercial Business',
   'yearBorn': 1973,
   'fiscalYear': 2025,
   'totalPay': 4490115,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 53,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 59,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Matthew  Kerner',
   'title': 'CTO & Corporate VP of Worldwide Sales and Solutions',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jonathan M. Palmer',
   'title': 'Corporate Vice President & Chief Legal Officer',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 7,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 2,
 'overallRisk': 5,
 'governanceEpochDate': 1788220800,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 495.63,
 'open': 497.5,
 'dayLow': 495.3416,
 'dayHigh': 509.93,
 'regularMarketPreviousClose': 495.63,
 'regularMarketOpen': 497.5,
 'regularMarketDayLow': 495.3416,
 'regularMarketDayHigh': 509.93,
 'dividendRate': 3.64,
 'dividendYield': 0.73,
 'exDividendDate': 1787184000,
 'payoutRatio': 0.1983,
 'fiveYearAvgDividendYield': 0.79,
 'beta': 1.108,
 'trailingPE': 28.17224,
 'forwardPE': 21.422323,
 'volume': 23020956,
 'regularMarketVolume': 23020956,
 'averageVolume': 35249503,
 'averageVolume10days': 19121080,
 'averageDailyVolume10Day': 19121080,
 'bid': 499.02,
 'ask': 507.41,
 'bidSize': 4,
 'askSize': 1,
 'marketCap': 3752944992256,
 'nonDilutedMarketCap': 3680323111704,
 'fiftyTwoWeekLow': 349.2,
 'fiftyTwoWeekHigh': 553.72,
 'allTimeHigh': 555.45,
 'allTimeLow': 0.088542,
 'fulldayPrice': 500.38,
 'fulldayChange': -5.010315,
 'fulldayChangePercent': -0.9913367,
 'priceToSalesTrailing12Months': 11.309535,
 'fiftyDayAverage': 455.9672,
 'twoHundredDayAverage': 431.4146,
 'trailingAnnualDividendRate': 3.64,
 'trailingAnnualDividendYield': 0.007344188,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3804915040256,
 'profitMargins': 0.40305,
 'floatShares': 7414407173,
 'sharesOutstanding': 7425545491,
 'sharesShort': 74451155,
 'sharesShortPriorMonth': 81311791,
 'sharesShortPreviousMonthDate': 1785456000,
 'dateShortInterest': 1788134400,
 'sharesPercentSharesOut': 0.01,
 'heldPercentInsiders': 0.00091,
 'heldPercentInstitutions': 0.75792,
 'shortRatio': 2.49,
 'shortPercentOfFloat': 0.01,
 'impliedSharesOutstanding': 7425545491,
 'bookValue': 59.565,
 'priceToBook': 8.485017,
 'lastFiscalYearEnd': 1782777600,
 'nextFiscalYearEnd': 1814313600,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': 0.313,
 'netIncomeToCommon': 133748998144,
 'trailingEps': 17.94,
 'forwardEps': 23.59268,
 'pegRatio': 1.61,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 11.466,
 'enterpriseToEbitda': 19.589,
 '52WeekChange': -0.019306898,
 'SandP52WeekChange': 0.15187562,
 'lastDividendValue': 0.91,
 'lastDividendDate': 1787184000,
 'quoteType': 'EQUITY',
 'currentPrice': 505.41,
 'targetHighPrice': 870.0,
 'targetLowPrice': 400.0,
 'targetMeanPrice': 572.91516,
 'targetMedianPrice': 555.0,
 'recommendationMean': 1.36364,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 52,
 'totalCash': 76842999808,
 'totalCashPerShare': 10.348,
 'ebitda': 194237005824,
 'totalDebt': 128812998656,
 'quickRatio': 1.099,
 'currentRatio': 1.23,
 'totalRevenue': 331839012864,
 'debtToEquity': 29.118,
 'revenuePerShare': 44.668,
 'returnOnAssets': 0.14088,
 'returnOnEquity': 0.34039003,
 'grossProfits': 225465008128,
 'freeCashflow': 16545500160,
 'operatingCashflow': 182934994944,
 'earningsGrowth': 0.317,
 'revenueGrowth': 0.177,
 'grossMargins': 0.67944,
 'ebitdaMargins': 0.58534,
 'operatingMargins': 0.45111,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'preMarketTime': 1789465880,
 'regularMarketTime': 1789416001,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'earningsTimestamp': 1785355200,
 'earningsTimestampStart': 1793217600,
 'earningsTimestampEnd': 1793217600,
 'earningsCallTimestampStart': 1785360600,
 'earningsCallTimestampEnd': 1785360600,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 17.94,
 'epsForward': 23.59268,
 'epsCurrentYear': 19.75972,
 'priceEpsCurrentYear': 25.577791,
 'fiftyDayAverageChange': 49.44281,
 'fiftyDayAverageChangePercent': 0.10843502,
 'twoHundredDayAverageChange': 73.99539,
 'twoHundredDayAverageChangePercent': 0.17151804,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.4 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'preMarketChange': -5.029999,
 'preMarketChangePercent': -0.99523133,
 'preMarketPrice': 500.38,
 'regularMarketChange': 9.78,
 'regularMarketDayRange': '495.3416 - 509.93',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 35249503,
 'fiftyTwoWeekLowChange': 156.20999,
 'fiftyTwoWeekLowChangePercent': 0.44733673,
 'fiftyTwoWeekRange': '349.2 - 553.72',
 'fiftyTwoWeekHighChange': -48.309967,
 'fiftyTwoWeekHighChangePercent': -0.08724621,
 'fiftyTwoWeekChangePercent': -1.9306898,
 'dividendDate': 1788998400,
 'marketState': 'PRE',
 'regularMarketChangePercent': 1.97325,
 'regularMarketPrice': 505.41,
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'displayName': 'Microsoft',
 'trailingPegRatio': 1.6096}

### Downdload the information about the symbol

In [14]:
response = yf.download('AAPL',start="2025-01-01",end="2025-12-31")

[*********************100%***********************]  1 of 1 completed

In [15]:
response

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2025-01-02  242.093140  247.305315  240.077766  247.136526  55740700
2025-01-03  241.606659  242.420743  240.147249  241.606659  40244100
2025-01-06  243.234848  245.548063  241.447813  242.549817  45045600
2025-01-07  240.464951  243.780883  239.611146  241.229392  40856000
2025-01-08  240.951401  241.954134  238.320499  240.177022  37628900
...                ...         ...         ...         ...       ...
2025-12-23  271.620667  271.760301  268.828279  270.104803  29642000
2025-12-24  273.066711  274.682309  271.461097  271.600701  17910600
2025-12-26  272.657806  274.622460  272.119264  273.415753  21521800
2025-12-29  273.016876  273.615223  271.610700  271.949773  23715200
2025-12-30  272.338684  273.335969  271.540868  272.069428  22139600

[249 rows x 5 columns]

In [17]:
prices = response['Close'].values
print(prices)

[[242.09313965]
 [241.60665894]
 [243.23484802]
 [240.46495056]
 [240.95140076]
 [235.14358521]
 [232.7111969 ]
 [231.59927368]
 [236.15618896]
 [226.615448  ]
 [228.32304382]
 [221.03593445]
 [222.21737671]
 [222.04858398]
 [221.1749115 ]
 [228.20391846]
 [236.54341125]
 [237.63546753]
 [235.8782196 ]
 [234.29966736]
 [226.36724854]
 [231.12275696]
 [230.79512024]
 [231.53973389]
 [225.99000549]
 [226.2583313 ]
 [231.19795227]
 [235.42196655]
 [240.05349731]
 [243.10470581]
 [242.9755249 ]
 [243.37306213]
 [244.32719421]
 [244.04890442]
 [245.58944702]
 [245.52980042]
 [238.89064026]
 [235.84934998]
 [240.36160278]
 [236.57489014]
 [234.48770142]
 [234.29888916]
 [233.89138794]
 [237.60852051]
 [226.08937073]
 [219.48995972]
 [215.65356445]
 [208.39819336]
 [212.18489075]
 [212.69178772]
 [211.38977051]
 [213.92420959]
 [212.79116821]
 [216.9356842 ]
 [219.38064575]
 [222.38218689]
 [220.17575073]
 [222.48158264]
 [216.56793213]
 [220.77207947]
 [221.82559204]
 [222.52131653]
 [201.94787598]
 [187.22840881]
 [180.35070801]
 [171.3659668 ]
 [197.63438416]
 [189.25593567]
 [196.93865967]
 [201.28196716]
 [200.90428162]
 [193.08239746]
 [195.77583313]
 [191.97920227]
 [198.51896667]
 [203.34925842]
 [207.09617615]
 [208.00064087]
 [208.8553772 ]
 [209.91885376]
 [211.20094299]
 [212.01596069]
 [204.09466553]
 [197.67416382]
 [197.29646301]
 [195.05029297]
 [196.2827301 ]
 [197.31634521]
 [209.77612305]
 [211.90585327]
 [211.30871582]
 [210.43295288]
 [210.24386597]
 [207.77580261]
 [205.86503601]
 [201.11798096]
 [200.39149475]
 [194.33078003]
 [199.24703979]
 [199.45600891]
 [198.98826599]
 [199.88394165]
 [200.7298584 ]
 [202.29232788]
 [201.84448242]
 [199.66500854]
 [202.93917847]
 [200.48104858]
 [201.69517517]
 [197.82391357]
 [198.24189758]
 [195.50511169]
 [197.46565247]
 [194.69902039]
 [195.63447571]
 [200.03321838]
 [200.5308075 ]
 [199.33657837]
 [200.5905304 ]
 [200.03321838]
 [200.112854  ]
 [204.1831665 ]
 [206.82043457]
 [211.41821289]
 [212.52285767]
 [208.94017029]
 [208.99987793]
 [210.12443542]
 [211.38833618]
 [210.14434814]
 [207.61656189]
 [208.10421753]
 [209.14915466]
 [209.00985718]
 [210.16424561]
 [211.45799255]
 [213.36875916]
 [213.11994934]
 [212.73184204]
 [212.85128784]
 [213.02044678]
 [210.25384521]
 [208.04450989]
 [206.5716095 ]
 [201.40660095]
 [202.37193298]
 [201.94398499]
 [212.2243042 ]
 [218.97171021]
 [228.24687195]
 [226.34388733]
 [228.80477905]
 [232.4712677 ]
 [231.92329407]
 [230.73765564]
 [230.04022217]
 [229.7114563 ]
 [225.17819214]
 [224.07226562]
 [226.92175293]
 [226.32397461]
 [228.46603394]
 [229.64172363]
 [231.7040863 ]
 [231.28562927]
 [228.87454224]
 [237.59234619]
 [238.89752197]
 [238.80784607]
 [237.0045166 ]
 [233.48748779]
 [225.95533752]
 [229.18341064]
 [233.20854187]
 [235.82884216]
 [237.27352905]
 [238.11042786]
 [237.0045166 ]
 [244.59646606]
 [255.13751221]
 [253.49357605]
 [251.38140869]
 [255.92460632]
 [254.51980591]
 [253.49357605]
 [253.69287109]
 [254.50985718]
 [256.18362427]
 [257.07037354]
 [255.74528503]
 [255.53607178]
 [257.11022949]
 [253.10502625]
 [244.36730957]
 [246.7485199 ]
 [246.85810852]
 [248.42233276]
 [246.53929138]
 [251.36146545]
 [261.27484131]
 [261.80291748]
 [257.49884033]
 [258.62463379]
 [261.85272217]
 [267.82070923]
 [268.01000977]
 [268.70739746]
 [270.40115356]
 [269.37493896]
 [268.05975342]
 [269.0461731 ]
 [269.14581299]
 [268.77713013]
 [267.48190308]
 [268.6986084 ]
 [274.50280762]
 [272.72763062]
 [272.20907593]
 [271.67050171]
 [266.73394775]
 [266.71405029]
 [267.83096313]
 [265.5272522 ]
 [270.75299072]
 [275.17102051]
 [276.21817017]
 [276.79656982]
 [278.0930481 ]
 [282.33151245]
 [285.41311646]
 [283.37866211]
 [279.9380188 ]
 [278.02325439]
 [277.13565063]
 [276.42758179]
 [278.02325439]
 [277.27526855]
 [277.52462769]
 [273.36587524]
 [273.86453247]
 [271.10205078]
 [271.45114136]
 [272.92712402]
 [270.23443604]
 [271.6206665 ]
 [273.06671143]
 [272.6578064 ]
 [273.01687622]
 [272.33868408]]

In [18]:
print(prices.shape)

(249, 1)